import type { ItemType } from "@/lib/league-city/types";

// 12×12 pixel icons for the hotbar, drawn from character grids so they stay
// crisp at any integer scale. "." is transparent.

type Sprite = { rows: string[]; palette: Record<string, string> };

const TRUNK = "#6b4226";
const SPRITES: Record<ItemType, Sprite> = {
  road: {
    rows: [
      "....aaaa....",
      "....aaaa....",
      "....ayya....",
      "aaaaaaaaaaaa",
      "aaaaaaaaaaaa",
      "ayyaaaaaayya",
      "aaaaaaaaaaaa",
      "aaaaaaaaaaaa",
      "....ayya....",
      "....aaaa....",
      "....aaaa....",
      "....aaaa....",
    ],
    palette: { a: "#3a4150", y: "#c8e64a" },
  },
  lamp: {
    rows: [
      "....yyyy....",
      "...yLLLLy...",
      "....yyyy....",
      ".....pp.....",
      ".....pp.....",
      ".....pp.....",
      ".....pp.....",
      ".....pp.....",
      ".....pp.....",
      ".....pp.....",
      "....pppp....",
      "...pppppp...",
    ],
    palette: { y: "#f0d870", L: "#fff4b0", p: "#7a7a86" },
  },
  bench: {
    rows: [
      "............",
      "............",
      "............",
      "wwwwwwwwwwww",
      "wwwwwwwwwwww",
      "............",
      "wwwwwwwwwwww",
      "WWWWWWWWWWWW",
      ".mm......mm.",
      ".mm......mm.",
      ".mm......mm.",
      "............",
    ],
    palette: { w: "#9a6a40", W: "#6b4226", m: "#4a4a52" },
  },
  fountain: {
    rows: [
      ".....bb.....",
      "....b..b....",
      "...b.bb.b...",
      ".....bb.....",
      "....gggg....",
      "....gbbg....",
      "..gggggggg..",
      ".gbbbbbbbbg.",
      ".gbbbbbbbbg.",
      ".gggggggggg.",
      "............",
      "............",
    ],
    palette: { b: "#5fb0f0", g: "#9a9aa6" },
  },
  ramp: {
    rows: [
      "............",
      "............",
      "............",
      "..........oo",
      "........oorr",
      "......oorrrr",
      "....oorrrrrr",
      "..oorrrrrrrr",
      "oorrrrrrrrrr",
      "RRRRRRRRRRRR",
      "............",
      "............",
    ],
    palette: { o: "#f0a030", r: "#c8703a", R: "#7a4a2a" },
  },
  ramp_big: {
    rows: [
      "............",
      "..........oo",
      ".........orr",
      "........orrr",
      ".......orrrr",
      "......orrrrr",
      ".....orrrrrr",
      "....orrrrrrr",
      "...orrrrrrrr",
      "..orrrrrrrrr",
      "RRRRRRRRRRRR",
      "............",
    ],
    palette: { o: "#f0a030", r: "#c8703a", R: "#7a4a2a" },
  },
  boost_pad: {
    rows: [
      "............",
      "..wwwwwwww..",
      "..wccccccw..",
      "..wccccccw..",
      "..wccccccw..",
      "..wccccccw..",
      "..wccccccw..",
      "..wccccccw..",
      "..wccccccw..",
      "..wccccccw..",
      "..wwwwwwww..",
      "............",
    ],
    palette: { w: "#b8f2ff", c: "#39d8ff" },
  },
  speed_bump: {
    rows: [
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "...yyyyyy...",
      "..ykkyykkyy.",
      ".yyyyyyyyyyy",
      "RRRRRRRRRRRR",
      "............",
      "............",
    ],
    palette: { y: "#f5c518", k: "#2a2a2a", R: "#3a4150" },
  },
  cone: {
    rows: [
      ".....oo.....",
      ".....oo.....",
      "....oooo....",
      "....wwww....",
      "....oooo....",
      "...oooooo...",
      "...wwwwww...",
      "...oooooo...",
      "..oooooooo..",
      ".kkkkkkkkkk.",
      ".kkkkkkkkkk.",
      "............",
    ],
    palette: { o: "#ff7a1a", w: "#f4f4f4", k: "#3a3a3a" },
  },
  crates: {
    rows: [
      "....bbbb....",
      "....bwwb....",
      "....bbbb....",
      "..bbbbbbbb..",
      "..bwwbbwwb..",
      "..bbbbbbbb..",
      "bbbbbbbbbbbb",
      "bwwbbwwbbwwb",
      "bwwbbwwbbwwb",
      "bbbbbbbbbbbb",
      "............",
      "............",
    ],
    palette: { b: "#7a4a24", w: "#b8844a" },
  },
  tire_wall: {
    rows: [
      "............",
      "............",
      "..kkkkkkkk..",
      ".kgkkgkkgkk.",
      ".kkkkkkkkkk.",
      "kkkkkkkkkkkk",
      "kgkkgkkgkkgk",
      "kkkkkkkkkkkk",
      "kkkkkkkkkkkk",
      "............",
      "............",
      "............",
    ],
    palette: { k: "#222228", g: "#6a6a78" },
  },
  plaza: {
    rows: [
      "............",
      "............",
      "ssssssssssss",
      "sSssSssSssSs",
      "ssssssssssss",
      "ssSssSssSsss",
      "ssssssssssss",
      "sSssSssSssSs",
      "ssssssssssss",
      "SSSSSSSSSSSS",
      "............",
      "............",
    ],
    palette: { s: "#8a90a0", S: "#686e7c" },
  },
  tree_default: {
    rows: [
      ".....gg.....",
      "....gggg....",
      "...gggggg...",
      "....gggg....",
      "...gggggg...",
      "..gggGgggg..",
      "...gggggg...",
      "..gggggggg..",
      ".gggGggggGg.",
      ".....tt.....",
      ".....tt.....",
      "....tttt....",
    ],
    palette: { g: "#3fa04a", G: "#2d7a36", t: TRUNK },
  },
  tree_oak: {
    rows: [
      "...gggggg...",
      "..gggGgggg..",
      ".gggggggggg.",
      ".ggGgggggGg.",
      "gggggggggggg",
      ".gggggGgggg.",
      "..gggggggg..",
      "....gggg....",
      ".....tt.....",
      ".....tt.....",
      ".....tt.....",
      "....tttt....",
    ],
    palette: { g: "#4cae3c", G: "#357e2a", t: TRUNK },
  },
  tree_fat: {
    rows: [
      "............",
      "....gggg....",
      "..gggggggg..",
      ".gggGgggggg.",
      "gggggggggggg",
      "gggggggGgggg",
      "gggGgggggggg",
      ".gggggggggg.",
      "..gggggggg..",
      ".....tt.....",
      ".....tt.....",
      "....tttt....",
    ],
    palette: { g: "#5cb845", G: "#3d8a2e", t: TRUNK },
  },
  tree_detailed: {
    rows: [
      "....gg......",
      "...gggg.gg..",
      "..gggggggggg",
      "...ggGggggg.",
      ".gggggg.gg..",
      "gggGggggg...",
      ".ggggg.gggg.",
      "...gg.ggGgg.",
      ".....tt.....",
      "....ttt.....",
      ".....tt.....",
      "....tttt....",
    ],
    palette: { g: "#44a852", G: "#2e7a3a", t: TRUNK },
  },
  tree_palm_tall: {
    rows: [
      "..gg....gg..",
      ".g..gggg..g.",
      "....g.gg....",
      "...g..t.g...",
      "......t.....",
      ".....t......",
      ".....t......",
      ".....t......",
      "......t.....",
      "......t.....",
      "......t.....",
      ".....ttt....",
    ],
    palette: { g: "#5cc05a", t: "#a07a4a" },
  },
  tree_pine_tall_a: {
    rows: [
      ".....gg.....",
      ".....gg.....",
      "....gggg....",
      "....gGgg....",
      "...gggggg...",
      "...ggggGg...",
      "..gggggggg..",
      "..gGgggggg..",
      ".gggggggggg.",
      ".....tt.....",
      ".....tt.....",
      "....tttt....",
    ],
    palette: { g: "#2f8a4a", G: "#1f6636", t: TRUNK },
  },
  portal: {
    rows: [
      "............",
      "bbbbbbbbbbbb",
      "bwwwwwwwwwwb",
      "bbbbbbbbbbbb",
      ".pl......lp.",
      ".pl......lp.",
      ".pl......lp.",
      ".pl......lp.",
      ".pl......lp.",
      ".pl......lp.",
      "mmmm....mmmm",
      "............",
    ],
    palette: { b: "#1b1f27", w: "#ffffff", p: "#232a36", l: "#c8e64a", m: "#3a3f4a" },
  },
  billboard: {
    rows: [
      "............",
      "ffffffffffff",
      "fLLLLwwwwwwf",
      "fLLLLwwwwwwf",
      "fLLLLwwwwwwf",
      "fLLLLwwwwwwf",
      "ffffffffffff",
      "..yy....yy..",
      "..m......m..",
      "..m......m..",
      "..m......m..",
      ".mmm....mmm.",
    ],
    palette: { f: "#1b1f27", L: "#c8e64a", w: "#8a93a6", y: "#fff3c4", m: "#3a3f4a" },
  },
  flag: {
    rows: [
      "..o.........",
      "..pcccccc...",
      "..pcLLLLcc..",
      "..pcLLLLccc.",
      "..pcLLLLcc..",
      "..pcccccc...",
      "..p.........",
      "..p.........",
      "..p.........",
      "..p.........",
      "..p.........",
      ".ppp........",
    ],
    palette: { o: "#e8c547", p: "#c9ccd2", c: "#2b3a67", L: "#c8e64a" },
  },
  blimp: {
    rows: [
      "............",
      "...hhhhhh...",
      ".hhhhhhhhhh.",
      "hhhllllllhhf",
      "hhllllllllhf",
      "hhhllllllhhf",
      ".hhhhhhhhhh.",
      "...hhhhhh...",
      ".....gg.....",
      "............",
      "............",
      "............",
    ],
    palette: { h: "#c0c8d0", l: "#c8e64a", f: "#8890a0", g: "#8890a0" },
  },
  plane: {
    rows: [
      "............",
      "..w.........",
      "..ww........",
      "wwwwwr......",
      "..ww.r......",
      "..w...r.....",
      "......llllll",
      "......llllll",
      "......llllll",
      "............",
      "............",
      "............",
    ],
    palette: { w: "#f4f1e8", r: "#8a93a6", l: "#c8e64a" },
  },
};

/** The hill sign isn't an object: a slot in the Identity tab that opens its panel. */
export function HillSignIcon({ size = 24 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 12 12" shapeRendering="crispEdges" aria-hidden>
      <rect x={0} y={9} width={12} height={3} fill="#2f5a3a" />
      <rect x={2} y={7} width={8} height={2} fill="#2f5a3a" />
      <rect x={1} y={4} width={2} height={3} fill="#f4f1e8" />
      <rect x={4} y={4} width={2} height={3} fill="#f4f1e8" />
      <rect x={7} y={4} width={2} height={3} fill="#f4f1e8" />
      <rect x={10} y={4} width={1} height={3} fill="#f4f1e8" />
    </svg>
  );
}

export function ItemIcon({ item, size = 24 }: { item: ItemType; size?: number }) {
  const { rows, palette } = SPRITES[item];
  const rects: React.ReactElement[] = [];
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const c = palette[row[x]];
      if (c) rects.push(<rect key={`${x}-${y}`} x={x} y={y} width={1} height={1} fill={c} />);
    }
  });
  return (
    <svg width={size} height={size} viewBox="0 0 12 12" shapeRendering="crispEdges" aria-hidden>
      {rects}
    </svg>
  );
}

export const ITEM_NAMES: Record<ItemType, string> = {
  road: "Road",
  lamp: "Lamp",
  bench: "Bench",
  fountain: "Fountain",
  plaza: "Plaza",
  ramp: "Ramp",
  ramp_big: "Big ramp",
  boost_pad: "Boost pad",
  speed_bump: "Speed bump",
  cone: "Cone",
  crates: "Crates",
  tire_wall: "Tire wall",
  tree_default: "Tree",
  tree_oak: "Oak",
  tree_fat: "Bush tree",
  tree_detailed: "Wild tree",
  tree_palm_tall: "Palm",
  tree_pine_tall_a: "Pine",
  portal: "Portal",
  billboard: "Billboard",
  flag: "Flag",
  plane: "Plane",
  blimp: "Blimp",
};
